[phases.setup]
nixPkgs = ["php81", "php81Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "chmod +x railway-start.sh"]

[start]
cmd = "php start-railway.php"

